name: Update Latest Blog Posts

on:
  schedule:
    # Once a day at 00:30 UTC
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull latest Medium posts into README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@adityakumar2019.ak"
          max_post_count: 5
          commit_message: "docs: update latest blog posts [skip ci]"
